import type { Product } from "@/types"

export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "Vitamin C 1000mg",
    slug: "vitamin-c-1000mg",
    description: "High-potency Vitamin C supplement to support immune health and antioxidant protection. Each tablet contains 1000mg of Vitamin C derived from natural sources. Supports collagen production, skin health, and iron absorption.",
    short_description: "Immune support with 1000mg Vitamin C per tablet",
    price: 45.90,
    compare_price: 59.90,
    images: ["/images/products/vitamin-c.jpg"],
    category: "Vitamins",
    stock_count: 150,
    weight_kg: 0.3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Omega-3 Fish Oil",
    slug: "omega-3-fish-oil",
    description: "Premium Omega-3 Fish Oil capsules with high EPA and DHA content. Supports heart health, brain function, and joint mobility. Molecularly distilled for purity and freshness.",
    short_description: "Heart & brain support with EPA/DHA",
    price: 68.00,
    compare_price: 85.00,
    images: ["/images/products/omega-3.jpg"],
    category: "Supplements",
    stock_count: 80,
    weight_kg: 0.4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Probiotics 50 Billion CFU",
    slug: "probiotics-50-billion",
    description: "Advanced probiotic formula with 50 billion CFU and 12 diverse strains. Supports digestive health, immune function, and nutrient absorption. Delayed-release capsules for maximum effectiveness.",
    short_description: "Gut health with 50 billion CFU probiotics",
    price: 89.90,
    compare_price: null,
    images: ["/images/products/probiotics.jpg"],
    category: "Gut Health",
    stock_count: 60,
    weight_kg: 0.2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Collagen Peptides Powder",
    slug: "collagen-peptides-powder",
    description: "Hydrolyzed collagen peptides for skin elasticity, hair growth, and joint support. Easily dissolves in hot or cold beverages. Sourced from grass-fed bovine collagen.",
    short_description: "Skin, hair & joint support collagen",
    price: 120.00,
    compare_price: 150.00,
    images: ["/images/products/collagen.jpg"],
    category: "Beauty",
    stock_count: 45,
    weight_kg: 0.5,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Magnesium Glycinate 400mg",
    slug: "magnesium-glycinate-400mg",
    description: "Highly absorbable magnesium glycinate for muscle relaxation, better sleep, and stress relief. Gentle on the stomach. Supports over 300 enzymatic reactions in the body.",
    short_description: "Better sleep & muscle relaxation",
    price: 55.00,
    compare_price: null,
    images: ["/images/products/magnesium.jpg"],
    category: "Minerals",
    stock_count: 100,
    weight_kg: 0.3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Multivitamin Complete",
    slug: "multivitamin-complete",
    description: "Comprehensive daily multivitamin with 25+ essential vitamins and minerals. Formulated for active adults. Includes B-complex for energy, Vitamin D3, Zinc, and antioxidants.",
    short_description: "Complete daily nutrition with 25+ nutrients",
    price: 75.00,
    compare_price: 95.00,
    images: ["/images/products/multivitamin.jpg"],
    category: "Vitamins",
    stock_count: 200,
    weight_kg: 0.35,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const categories = ["All", "Vitamins", "Supplements", "Gut Health", "Beauty", "Minerals"]
